### PR TITLE
Add seasocks v1.4.5

### PR DESCRIPTION
**Pull request by iris-ersc**
Build with:

bitbake mc:imx8mp-irma6r2:seasocks

Check if build successful:
... build/tmp/work/cortexa53-crypto-poky-linux/seasocks/1.4.5-r0/package/usr/lib/libseasocks.so.1.4.5

### CODE REVIEW

**Review by Eximmius — APPROVED** [review]

**Review by Jasper-Ben — CHANGES_REQUESTED** [review]
:wave: @iris-ersc,

please remember, that patches to software in this repository should be as close as possible to upstream and limited to the bare minimum of making them compile and run on Yocto. Any feature patches should be ideally upstreamed to the software in question or added in the meta-iris-base repository. The latter seems to be the case to me with the patches included here.

**Comment by iris-ersc** [comment]
> please remember, that patches to software in this repository should be as close as possible to upstream and limited to the bare minimum of making them compile and run on Yocto. Any feature patches should be ideally upstreamed to the software in question or added in the meta-iris-base repository. The latter seems to be the case to me with the patches included here.

This pull request contains the same patches as the already existing 1.4.4 recipe. They were simply updated to match the 1.4.5 sources. One patch could be dropped.
But I can move all of them to meta-iris-base

**Comment by Jasper-Ben** [comment]
> > please remember, that patches to software in this repository should be as close as possible to upstream and limited to the bare minimum of making them compile and run on Yocto. Any feature patches should be ideally upstreamed to the software in question or added in the meta-iris-base repository. The latter seems to be the case to me with the patches included here.
> 
> This pull request contains the same patches as the already existing 1.4.4 recipe. They were simply updated to match the 1.4.5 sources. One patch could be dropped. But I can move all of them to meta-iris-base

Oh, then they shouldn't have been there in the first place. This layer is only meant to add Yocto support for upstream software and should provide a vanilla experience. Would you be so kind to also move the 1.4.4 patches to meta-iris-base then?

**Comment by Jasper-Ben** [comment]
Please remove task name :)

**Comment by iris-ersc** [comment]
Conflicts resolved, task number removed, seasocks patches extraced.

**Comment by Jasper-Ben** [comment]
I removed yaml-cpp, as this is dunfell specific. Since hardknott, it is part of [meta-oe](https://layers.openembedded.org/layerindex/recipe/163426/)  and we should use the upstream recipe.

**Review by Jasper-Ben — APPROVED** [review]
LGTM

**Pull request merged**
